function opts = RCAC_ESC_RLS_SISO_define_opts()
    
    lu = 1;                 % Single input
    lz = 1;                 % Single output
    indi = 3;               % Delay for gradient estimation
    P0_G = 1e-3*eye(2);     % Initial RLS covariance for gradient estimation
    
    Nc = 5;                 % Controller window length
    P0_C = 1e-1;            % Controller initial covariance
    Ru = 0.05;              % Controller output weight
    nu = 0.2;               % Normalization parameter for controller performance variable

    epsi = 1e-3;            % Minimal gradient norm

    opts = struct('lu',         lu,...
                  'lz',         lz,...
                  'indi',       indi,...
                  'P0_G',       P0_G,...
                  'Nc',         Nc,...
                  'P0_C',       P0_C,...
                  'Ru',         Ru,...
                  'nu',         nu,...
                  'epsi',       epsi);

end