function opts = RCAC_PID_ESC_fixed_Nf_KF_MISO_define_opts()
    
    lu = 2;                 % Two inputs
    lz_grad = 1;                 % Single output
    indi = [2 6];               % Delay for gradient estimation
    P0_G = 1e-4*eye(3);     % Initial KF covariance
    Q = 1e-1*eye(3);        % Q matrix for KF
    R = 1e-1*eye(3);         % R marix for KF
    
    lz_cont = 2;                 % For gradient as perfromaance variable z
    PID_flag = [2 2 ;2 2];           % P = 1, PI = 2, PID = 3.
    P0_C = 1e-3;            % Controller initial covariance
    Ru = 0.55;              % Controller output weight
    nu = 0.2;               % Normalization parameter for controller performance variable

    nf_diag = [-1 -1 ; -1 -1];           %Gf filter coefficients (lz-by-lu)
    
    epsi = 1e-3;            % Minimal gradient norm

    opts = struct('lu',         lu,...
                  'lz_grad',    lz_grad,...
                  'indi',       indi,...
                  'P0_G',       P0_G,...
                  'Q',          Q,...
                  'R',          R,...
                  'lz_cont',    lz_cont,...
                  'PID_flag',   PID_flag,...
                  'P0_C',       P0_C,...
                  'Ru',         Ru,...
                  'nu',         nu,...
                  'nf_diag',    nf_diag,...
                  'epsi',       epsi);

end