function opts = RCAC_ESC_RLS_MISO_define_opts()
    
    lu = 2;                 % Two inputs
    lz = 1;                 % Single output
    indi = [2 6];               % Delay for gradient estimation
    P0_G = 1e-2*eye(3);     % Initial RLS covariance for gradient estimation
    
    Nc = 8;                 % Controller window length, Max Nc = 10, can adjust by increasing theta_out size in RCAC_ESC Simulink block
    P0_C = 1e-2;            % Controller initial covariance
    Ru = 0.325;              % Controller output weight
    nu = 0.2;               % Normalization parameter for controller performance variable

    epsi = 1e-3;            % Minimal gradient norm

    opts = struct('lu',         lu,...
                  'lz',         lz,...
                  'indi',       indi,...
                  'P0_G',       P0_G,...
                  'Nc',         Nc,...
                  'P0_C',       P0_C,...
                  'Ru',         Ru,...
                  'nu',         nu,...
                  'epsi',       epsi);

end