function opts = RCAC_ESC_KF_SISO_define_opts()
    
    lu = 1;                 % Single input
    lz = 1;                 % Single output
    indi = 3;               % Delay for gradient estimation
    P0_G = 1e-3*eye(2);     % Initial KF covariance
    Q = 1e-1*eye(2);        % Q matrix for KF
    R = 1e1*eye(2);         % R marix for KF
    
    Nc = 5;                 % Controller window length, Max Nc = 10, can adjust by increasing theta_out size in RCAC_ESC Simulink block
    P0_C = 1e-1;            % Controller initial covariance
    P0_C = 1e-5;            % Controller initial covariance
    Ru = 0.05;              % Controller output weight
    nu = 0.2;               % Normalization parameter for controller performance variable

    epsi = 1e-3;            % Minimal gradient norm

    opts = struct('lu',         lu,...
                  'lz',         lz,...
                  'indi',       indi,...
                  'P0_G',       P0_G,...
                  'Q',          Q,...
                  'R',          R,...
                  'Nc',         Nc,...
                  'P0_C',       P0_C,...
                  'Ru',         Ru,...
                  'nu',         nu,...
                  'epsi',       epsi);

end